### ISSUE TITLE
IP addresses being duplicated

### ISSUE THREAD

**Issue by bitcoinfees** [zarvox/piwik#1]
First off, nice job!  Loving the ability to launch a Piwik instance so easily.

The issue:

I'm seeing IP addresses being duplicated across multiple visitors.  It looks like after the first visitor has arrived, subsequent visitors' IP addresses are identical to that of the first user.

Occasionally it resets - the IP address becomes correct, but then subsequently all IP address take on that same value again.

[This](https://oasis.sandstorm.io/grain/8hmQyF9mHLgZc6opMLyypu/) is the grain in question; if you like I can grant you access.

**Comment by dwrensha** [comment]
I believe this is fixed now.
