### ISSUE TITLE
no geographical informations

### ISSUE THREAD

**Issue by mrflos** [zarvox/piwik#10]
Hello,
I have a sandstorm installed with nginx proxy on http (not https) and i cannot collect geographical informations : the map is empty...  
Other fields are ok.  

I tried a piwik grain on oasis, and i seems to work there.  

Is this problem coming from my vps provider or do you have any hint?  

Thanks a lot!

**Comment by zarvox** [comment]
The geolocation support uses the IP address of the viewer.  If you're proxying through nginx, you'll need to configure nginx to pass on the remote address in a header, since Sandstorm otherwise won't have access to that information:

```
proxy_set_header X-Real-IP $remote_addr;
```

**Comment by mrflos** [comment]
Great!  
Thanks a lot @zarvox !

Should I submit a PR for the [sandstorm docs nginx config sample file](https://github.com/sandstorm-io/sandstorm/blob/cfb91bd8f189ba89221d770677ae0244b0e81317/docs/administering/sample-config/nginx-example.conf) ?

Here is my related nginx configuration that seems to work :

```
# we're in the http context here
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

server {
        listen *:80;

        server_name sandstorm.example.com ~^sandstorm-[^.]*\.example\.com$ *.sandstorm.example.com;

        location / {
            proxy_pass http://127.0.0.1:6080;
            proxy_set_header Host $http_host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
        }
}
```

**Comment by zarvox** [comment]
Closing this issue here, since things seem to be sorted out. :)
