### ISSUE TITLE
HTTP 504 errors

### ISSUE THREAD

**Issue by pgrm** [zarvox/piwik#3]
Hi, this is a great tool, but somehow I think I've outgrown it.

My web app doesn't have too many users, but I open PIWIK only every month or so, which means that it needs to recalculate all the data collected in the meanwhile, if I understood it correctly.

This used to work, but right now I'm just getting **504 Gateway Time-out**

The server on which sandstorm is running is a core i5 quad core with 16GB memory and bored as hell. I didn't see any CPU spike or anything similar, while PIWIK was loading. Is there any way I could dedicate more resources to that app? Or any other way to make it work again?

Thank you

**Comment by zarvox** [comment]
Hmmm, that's odd.  When you open the grain, can you click on the "Show Debug Log" button (the little computer screen button in the toolbar), and share what's logged there?

In the event that something went awry in either the Piwik startup or migrations code, it'd be logged there, and might keep Piwik from actually starting up successfully, which would explain why there's no observable CPU spike, but no backend answering the request.  Either way, seeing the logs would help me figure out what's going on.

You can also take a backup of the grain with the "Download Backup" button (the down arrow button in the toolbar).  This will fetch a .zip file containing all of the app's logs (not just the most recent snippet), which might be useful if the "Show Debug Log" window is cut off, as well as the MySQL database in which all of Piwik's data is stored.

**Comment by pgrm** [comment]
sorry for bugging you - later i realized that my sever was kinda screwed up - reporting loads of 3-5 while the cpu barely reached 5%

I've reseted everything with a fresh ubuntu 16.04 now and everything seems working - it's soo much faster now :) - don't understand how I could stand using it so slow for so long - thx again, and seems everything is working just fine now

**Comment by zarvox** [comment]
Great, I'm glad to hear things are working well now! :)
