### ISSUE TITLE
Small /tmp crashes most widgets on high traffic

### ISSUE THREAD

**Issue by FiloSottile** [zarvox/piwik#8]
On days of high traffic (say, 20k visits), the "Visits over time", "Page Titles" and "Referer websites" widgets fail with

```
SQLSTATE[HY000]: General error: 3 Error writing file '/tmp/MYoIH0GW' (Errcode: 28) - caused by plugin Referrers
```

I suspect this is due to a full /tmp filesystem. See sandstorm-io/sandstorm#553

**Comment by zarvox** [comment]
Hi!  Thanks for filing this issue.

I've just published an app update for Piwik (version 2.15.0-sandstorm-6) that moves the MySQL tmpdir to `/var/tmp` - you can either install the latest version from the [App Market](https://apps.sandstorm.io/app/xuajusd5d4a9v4js71ru0cwj9wn984q1x8kny10htsp8f5dcfep0) now, or you can wait up to 24 hours for your server to check for app updates and click the "Apply updates" button from within your Sandstorm UI to make the update go live for your grains.

P.S. I enjoy reading your blog posts every time they pop up on HN!  Glad to see Piwik on Sandstorm is serving you (mostly) well. :)

**Comment by FiloSottile** [comment]
Thanks for the super-quick turnaround, high traffic days are now successfully processed!

> P.S. I enjoy reading your blog posts every time they pop up on HN! Glad to see Piwik on Sandstorm is serving you (mostly) well. :)

Thanks! This article is there thanks to Piwik on Sandstorm: https://blog.filippo.io/self-host-analytics/ :)

**Comment by paulproteus** [comment]
@zarvox Out of curiosity, would you be +1 on doing this for MySQL across all future vagrant-spk VMs?

**Comment by zarvox** [comment]
@paulproteus done, https://github.com/sandstorm-io/vagrant-spk/pull/187
